print (' ------------------------------------------------ ')
print ('|                                                |')
print ('|    02GoodbyeWorld                              |') 
print ('|    Name : Celestine Sutanto                    |')
print ('|    Version : 01                                |')
print ('|                                                |')
print (' ------------------------------------------------ ')
print ('Hello World')
x = input('------> Program paused - press enter to continue')
print('Goodbye World')
