print (' ------------------------------------------------ ')
print ('|                                                |')
print ('|    05forLoop                                   |') 
print ('|    Name : Celestine Sutanto                    |')
print ('|    Version : 01                                |')
print ('|                                                |')
print (' ------------------------------------------------ ')